### ISSUE TITLE
spack package and release policy

### ISSUE THREAD

**Issue by bd4** [disheng222/SZ#11]
I created a spack package for SZ in a fork, and would like to submit a pull request soon:
https://github.com/bd4/spack

Tarballs changing without the version also changing is problematic for spack packages, because the spack package definition has a tarball checksum associated with each version. Is 1.4.9-beta ready, and if so can it be frozen so any further changes get a new version number?

**Comment by disheng222** [comment]
Hi Bryce,
Good question.
OK. You can go ahead and SZ 1.4.9-beta is frozen.
I will use another number such as SZ1.4.9.1 or SZ1.4.10 in the future.

I think there are probably no issues (hopefully) on the code, thanks to
your previous feedback!

Best,
Sheng

2017-02-27 13:17 GMT-06:00 Bryce Allen <notifications@github.com>:
