### ISSUE TITLE
Error with "this" keyword in TightDataPointStorageI.h

### ISSUE THREAD

**Issue by jychoi-hpc** [disheng222/SZ#19]
I got the following error when I tried to compile SZ with a c++ application:
/Users/jyc/sw/sz/1.4.11.0/clang/include/TightDataPointStorageI.h:47:58: error: expected ')'
void new_TightDataPointStorageI(TightDataPointStorageI **this,
                                                         ^
/Users/jyc/sw/sz/1.4.11.0/clang/include/TightDataPointStorageI.h:47:32: note: to match this '('
void new_TightDataPointStorageI(TightDataPointStorageI **this,

It turned out "this" keyword in TightDataPointStorageI.h causing the error with c++. If I simply remove "this" in the header, it worked. Can SZ remove "this" keyword in the header files?

**Comment by dingwentao** [comment]
Jong, could you please update and try the code again?

**Comment by jychoi-hpc** [comment]
Yes, it works now. Thank you for the quick fix.
