### ISSUE TITLE
Build failing on Summit

### ISSUE THREAD

**Issue by kshitij-v-mehta** [disheng222/SZ#26]
Build fails on Summit with gcc 8.1.0 with the following message:

```
../../zstd/./decompress/zstd_decompress.c:59:10: fatal error: cpu.h: No such file or directory
 #include "cpu.h"
           ^~~~~~~
compilation terminated.
```

**Comment by disheng222** [comment]
Did you try to compile it using ./configure;make; or cmake? It seems that problem comes from zstd package: missing cpu.h, which actually can be found in this directory: zstd/common.

**Comment by kshitij-v-mehta** [comment]
Build fails on a local machine as well. I am using configure from a dedicated build directory.
If I run configure and make directly from the source directory, I get a different error:

```
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..    -I./include -I../zlib/ -I../zstd/       -O3 -std=c99 -Wall -MT src/libSZ_la-ArithmeticCoding.lo -MD -MP -MF src/.deps/libSZ_la-ArithmeticCoding.Tpo -c -o src/libSZ_la-ArithmeticCoding.lo `test -f 'src/ArithmeticCoding.c' || echo './'`src/ArithmeticCoding.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I./include -I../zlib/ -I../zstd/ -O3 -std=c99 -Wall -MT src/libSZ_la-ArithmeticCoding.lo -MD -MP -MF src/.deps/libSZ_la-ArithmeticCoding.Tpo -c src/ArithmeticCoding.c  -fPIC -DPIC -o src/.libs/libSZ_la-ArithmeticCoding.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I./include -I../zlib/ -I../zstd/ -O3 -std=c99 -Wall -MT src/libSZ_la-ArithmeticCoding.lo -MD -MP -MF src/.deps/libSZ_la-ArithmeticCoding.Tpo -c src/ArithmeticCoding.c -o src/libSZ_la-ArithmeticCoding.o >/dev/null 2>&1
mv -f src/.deps/libSZ_la-ArithmeticCoding.Tpo src/.deps/libSZ_la-ArithmeticCoding.Plo
/bin/bash ../libtool --tag=FC --mode=link  -I./include -I../zlib/ -I../zstd/       -O3 -version-info  1:4:0 -o libSZ.la -rpath /home/kmehta/vshare/opt/SZ-master-01.13.19/installation/lib src/libSZ_la-ByteToolkit.lo src/libSZ_la-dataCompression.lo src/libSZ_la-DynamicIntArray.lo src/libSZ_la-iniparser.lo src/libSZ_la-szf.lo src/libSZ_la-CompressElement.lo src/libSZ_la-DynamicByteArray.lo src/libSZ_la-rw.lo src/libSZ_la-utility.lo src/libSZ_la-TightDataPointStorageI.lo src/libSZ_la-TightDataPointStorageD.lo src/libSZ_la-TightDataPointStorageF.lo src/libSZ_la-conf.lo src/libSZ_la-DynamicDoubleArray.lo src/libSZ_la-rwf.lo src/libSZ_la-TypeManager.lo src/libSZ_la-dictionary.lo src/libSZ_la-DynamicFloatArray.lo src/libSZ_la-VarSet.lo src/libSZ_la-callZlib.lo src/libSZ_la-Huffman.lo src/libSZ_la-sz_float.lo src/libSZ_la-sz_double.lo src/libSZ_la-sz_int8.lo src/libSZ_la-sz_int16.lo src/libSZ_la-sz_int32.lo src/libSZ_la-sz_int64.lo src/libSZ_la-sz_uint8.lo src/libSZ_la-sz_uint16.lo src/libSZ_la-sz_uint32.lo src/libSZ_la-sz_uint64.lo src/libSZ_la-szd_uint8.lo src/libSZ_la-szd_uint16.lo src/libSZ_la-szd_uint32.lo src/libSZ_la-szd_uint64.lo src/libSZ_la-szd_float.lo src/libSZ_la-szd_double.lo src/libSZ_la-szd_int8.lo src/libSZ_la-szd_int16.lo src/libSZ_la-szd_int32.lo src/libSZ_la-szd_int64.lo src/libSZ_la-sz.lo src/libSZ_la-sz_float_pwr.lo src/libSZ_la-sz_double_pwr.lo src/libSZ_la-szd_float_pwr.lo src/libSZ_la-szd_double_pwr.lo src/libSZ_la-ArithmeticCoding.lo     
Usage: /home/kmehta/vshare/opt/SZ-master-01.13.19/libtool [OPTION]... [MODE-ARG]...
Try 'libtool --help' for more information.
libtool:   error: unrecognised option: '-I./include'
Makefile:736: recipe for target 'libSZ.la' failed
```

**Comment by disheng222** [comment]
Hi Kshitij,
Did you compile the package according to the user guide? For example:
./configure --prefix=.....
make && make install

What do you mean by "make directly from the source directory"?

Best,
Sheng

**Comment by louiswicker** [comment]
Does the netCDF reader convert files?  And has the API changed since its writing?  I have gotten the SZ package to compile, but I get the following errors:

(wof-test) [louis.wicker@wof-post2]/home/louis.wicker/SZ/NetCDFReader(220): make -f Makefile.linux
gcc -o test/test_NetCDFReader test/test_NetCDFReader.c -I./include -L. -lnetcdfreader -I/usr/local/netcdf/include -L/usr/local/netcdf/lib -lnetcdf -I/home/louis.wicker/SZ/include -L/home/louis.wicker/SZ/lib -lSZ -lzlib
/home/louis.wicker/SZ/lib/libSZ.so: undefined reference to `ZSTD_getFrameContentSize'
/home/louis.wicker/SZ/lib/libSZ.so: undefined reference to `ZSTD_compress'
/home/louis.wicker/SZ/lib/libSZ.so: undefined reference to `ZSTD_decompress'
collect2: error: ld returned 1 exit status
make: *** [test/test_NetCDFReader] Error 1

I can run the Travis-CI tests succesfully, but when I do an nm on the libSZ, I get,
$ nm libSZ.so | grep ZSTD
                 U ZSTD_compress
                 U ZSTD_decompress
                 U ZSTD_getFrameContentSize

Any ideas?

**Comment by disheng222** [comment]
I noted that the line 3 of Makefile.linux was missing -lzstd.
You can replace "ZFLAGS = -L$(SZPATH)/lib -lSZ -lzlib" by "ZFLAGS = -L$(SZPATH)/lib -lSZ -lzlib -lzstd", then the problem should be resolved. I revised Makefile.linux. You can update your repo by "git pull", and recompile it. It should be fine now.

In fact, the NetCDFReader in the SZ package just converts the NetCDF files to binary files such that you can use sz command to do the compression and decompression. If you have a netcdf file, alternatively, you can use "PNetCDF-SZ" (https://github.com/Parallel-NetCDF/PnetCDF-SZ).
PnetCDF-SZ can read the PnetCDF files in parallel (by MPI ranks) and store the compressed data in another netcdf file. You can also decompress it conveniently. Hope this information is helpful.
