### ISSUE TITLE
SZ fails to losslessly compress/decompress data

### ISSUE THREAD

**Issue by martinradev** [disheng222/SZ#28]
SZ fails to losslessly compress/decompress data.

Input file: ```http://www.cs.txstate.edu/~burtscher/research/datasets/FPsingle/msg_sppm.sp.spdp```
Note that the file is compressed with SPDP. You have to decompress it first.

To compress I used the following command:
```./sz -i /msg_sppm.sp -f -z tmp.data -1 34874483 -A .0 -p```
```compression time = 0.887475
compressed data file: tmp.data
=================SZ Compression Meta Data=================
Version:                        	 40.181.47
Constant data?:                 	 YES
Lossless?:                      	 YES
Size type (size of # elements): 	 8 bytes
Num of elements:                	 1391624735126898859
Data type:                      	 FLOAT
quantization_intervals:         	 145244089
max_quant_intervals:            	 - 0
dataEndianType (prior raw data):	 LITTLE_ENDIAN
sysEndianType (at compression): 	 LITTLE_ENDIAN
sampleDistance:                 	 20723
predThreshold:                  	 2.573500
szMode:                         	 SZ_BEST_SPEED (without Gzip)
gzipMode:                       	 Z_BEST_SPEED
errBoundMode:                   	 ABS
absErrBound:                    	 -11068089228422190989312.000000
```

To decompress I ran:
```./sz -z tmp.data -x tmp_decompressed.data -1 34874483 -p -A .0```
```decompressed data file: tmp_decompressed.data
=================SZ Compression Meta Data=================
Version:                        	 2.1.3
Constant data?:                 	 NO
Lossless?:                      	 NO
Size type (size of # elements): 	 8 bytes
Num of elements:                	 34874483
Data type:                      	 FLOAT
quantization_intervals:         	 65536
max_quant_intervals:            	 - 0
dataEndianType (prior raw data):	 LITTLE_ENDIAN
sysEndianType (at compression): 	 LITTLE_ENDIAN
sampleDistance:                 	 100
predThreshold:                  	 0.990000
szMode:                         	 SZ_BEST_COMPRESSION (with Gzip)
gzipMode:                       	 Z_BEST_SPEED
errBoundMode:                   	 ABS
absErrBound:                    	 0.000719
```

There's a significant difference after a given index in the decompressed data.

Any ideas what could be causing this?
I initially discovered the bug when using the API and reproduced it using the utility binary provided in the project.

**Comment by disheng222** [comment]
Hi,
SZ doesn't support lossless compression.
Setting error bound to 0.0 will definitely cause issues. Maybe we can add a
checking to see if the error bound == 0 before the lossy compression in our
code. If it's 0, we can let the compression use zstd instead. Does this
solution work for you?

Best,
Sheng

**Comment by martinradev** [comment]
Thanks for your reply.
The output from the sz utility " Lossless? YES" seems to hint that the original data should be recoverable but it was not. To me this looks like a bug.

If you want to support lossless compression, the design is up to you. I do not expect ZSTD on its own to lead to good results for FP data.

**Comment by disheng222** [comment]
Hi,
Strictly speaking, SZ doesn't support lossless compression.
In fact, SZ includes four steps: 1. prediction; 2. quantization; 3. Huffman
encoding; 4. Zstd compression (lossless compression).
After all the above four steps, SZ will check if the compressed size is
smaller than the original data size. If it is not, SZ will just discard the
compressed data and then compress the original data by Zstd. In this case,
the output bytes would be lossless compression mode. This is why we have a
'lossless indicator' in the output data. The error bound should not be 0.0
in the setting.

Best,
Sheng

**Comment by martinradev** [comment]
Thanks, I'm closing the issue.
