### ISSUE TITLE
confusing libtool error when fortran compiler is not present

### ISSUE THREAD

**Issue by bd4** [disheng222/SZ#4]
If the fortran compiler is missing, configure still succeeds but make fails when invoking libtool with this stumper:

```
/bin/bash ../libtool  --tag=FC   --mode=link    -version-info  1:4:0  -o libsz.la -rpath /usr/local/lib libsz_la-ByteToolkit.lo libsz_la-dataCompression.lo libsz_la-DynamicIntArray.lo libsz_la-iniparser.lo libsz_la-CompressElement.lo libsz_la-DynamicByteArray.lo libsz_la-rw.lo libsz_la-TightDataPointStorageD.lo libsz_la-TightDataPointStorageF.lo libsz_la-conf.lo libsz_la-DynamicDoubleArray.lo libsz_la-TypeManager.lo libsz_la-dictionary.lo libsz_la-DynamicFloatArray.lo libsz_la-VarSet.lo libsz_la-test_zlib.lo libsz_la-Huffman.lo libsz_la-sz_float.lo libsz_la-sz_double.lo libsz_la-sz.lo libsz_la-TightDataPointStorageF_pwr.lo libsz_la-TightDataPointStorageD_pwr.lo libsz_la-sz_float_pwr.lo libsz_la-sz_double_pwr.lo  
libtool: link: unrecognized option `-ersion-info'
```
My best guess is that there is something missing in the autoconf dependencies that is allowing this to happen.

EDIT: this is using the sz-1.4.9-beta tarball, using just `./configure`, without enable fortran option.

**Comment by disheng222** [comment]
Hi Bryce,
Do you need the fortran version?
If you just need the C version, you can run "./configure --prefix=xxx", but
if you need fortran interface, you need to use --enable-fortran in this
step.
I remember the above issue happened before, but fixed thereafter. So,
please download the new version 1.4.9 again to see if it's still there.
Thanks.

Best,
Sheng

2017-02-08 15:15 GMT-06:00 Bryce Allen <notifications@github.com>:

**Comment by bd4** [comment]
I only need the C version. I tried again using a fresh download (from http://www.mcs.anl.gov/~shdi/download/sz-1.4.9-beta.tar.gz), and get the same error. Maybe something is going wrong with the FORTRAN variable being passed around to sub-directory automake? I'm trying to figure out how to print the value of an automake variable.

**Comment by bd4** [comment]
Seems like this should be wrapped in `@FORTRAN_TRUE@` in the `Makefile.in` and have an alternate FALSE version:
https://github.com/disheng222/SZ/blob/master/sz/Makefile.in#L180

It's not obvious to me what in the `Makefile.am` is resulting in this not happening. Maybe just needs a re-run of automake?

**Comment by bd4** [comment]
It looks like automake is detecting fortran code, and using the fortran linker:
https://www.gnu.org/software/automake/manual/html_node/How-the-Linker-is-Chosen.html
A quick review of the files listed in `sz/Makefile.am` does not yield anything that is obviously fortran, so not sure why it is detecting it that way.

Also I can't find any docs on `LIDADD` - shouldn't that be either `LDADD` or `LIBADD`?

**Comment by disheng222** [comment]
Hi,
I just tested it on a Linux machine without fortran installed, and it works
successfully.
I guess you are using mac because my friend said he ran into the above
error before and solved it after installing fortran.

Best,
Sheng

2017-02-08 16:18 GMT-06:00 Bryce Allen <notifications@github.com>:

**Comment by disheng222** [comment]
Hi,
I can reproduce it on a mac without fortran.
Let me figure it out.

Best,
Sheng

2017-02-08 17:30 GMT-06:00 Sheng Di <disheng222@gmail.com>:

**Comment by bd4** [comment]
I'm testing on two Linux machines - one is a VM running Arch Linux, the other is Ubuntu 16.04, and both have the issue. So not limited to Mac, but glad you can reproduce. Let me know if I can do anything to help.

**Comment by disheng222** [comment]
Hi,
You can download
http://www.mcs.anl.gov/~shdi/download/sz-1.4.8-nofortran.tar.gz
It works on my the mac without fortran.
The difference between 1.4.9 and 1.4.8 is that 1.4.9 added one more
error-bound-mode (allowing 'point-wise relative error bound' compression).

Best,
Sheng

2017-02-08 17:45 GMT-06:00 Bryce Allen <notifications@github.com>:

**Comment by disheng222** [comment]
Hi,
I just created a nofortran-version for SZ 1.4.9.
You can download it from here:
http://www.mcs.anl.gov/~shdi/download/sz-1.4.9-nofortran.tar.gz
It works normally for me, so hope it works for you too.

Best,
Sheng

2017-02-08 17:49 GMT-06:00 Sheng Di <disheng222@gmail.com>:

**Comment by disheng222** [comment]
Hi,
OK. I solved the problem.
You can download sz-1.4.9-beta.tar.gz again (from website or github), and
now it should be linked  to C compiler by default.
Should you have any more problems, feel free to let me know.
Thanks for pointing this issue out!

Best,
Sheng

2017-02-08 18:04 GMT-06:00 Sheng Di <disheng222@gmail.com>:

**Comment by bd4** [comment]
That fixed the issue, thanks!
