### ISSUE TITLE
Missing parentheses in function convertBytesToSZParams

### ISSUE THREAD

**Issue by jw447** [disheng222/SZ#46]
It seems that in ByteToolkit.c, function convertBytesToSZParams(unsigned char* bytes, sz_params* params), line 963 should be 

> exe_params->optQuantMode = (flag1 & 0x40) >> 6;

Missing parentheses will cause incorrect optQuantMode.

**Comment by disheng222** [comment]
Thanks, Jon.
You are right. I just fixed it. Missing that parenthesis only causes wrong
metadata in the compressed data but not affect the decompressed data or
compression ratio.

Best,
Sheng

**Comment by jw447** [comment]
Thank you @disheng222 for the response.
