### ISSUE TITLE
Makefile change to build libhdf5sz.so

### ISSUE THREAD

**Issue by ajelenak** [disheng222/SZ#57]
Hello!

Building shared `libhdf5sz.so` library failed for me due to missing symbols from the HDF5 library. Below is the altered build [command](https://github.com/disheng222/SZ/blob/fbe4d0162c1ffb0dc25c3af164ee83eee41da823/hdf5-filter/H5Z-SZ/Makefile#L56) that worked:
```
$(CC) -O3 -shared -o $(LIB)/$(SHARED) $(OBJS) $(SZFLAGS) -L$(HDF5PATH)/lib -lc -lSZ -lhdf5 -lzlib -lzstd
```

**Comment by disheng222** [comment]
Thanks for pointing out this possible compilation issue. I guess that's due
to different compilers, because the original command also worked on
different platforms. I used your recommended one, which also works OK on my
testing machines. So, I committed this change.
