### ISSUE TITLE
unable to build from github checkout

### ISSUE THREAD

**Issue by bd4** [disheng222/SZ#6]
I can run `./configure`, but I get the following error when running `make`:

```
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /home/bda/codar/SZ/missing aclocal-1.13 
/home/bda/codar/SZ/missing: line 81: aclocal-1.13: command not found
WARNING: 'aclocal-1.13' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [Makefile:349: aclocal.m4] Error 127
```

There are also several files checked into source control that should probably be removed and ignored. After running `./configure`, the following files are modified:

```
	modified:   Makefile
	modified:   config.log
	modified:   config.status
	modified:   libtool
```

**Comment by bd4** [comment]
To clarify, this does not happen with the 1.4.9 tarball download. I think that aclocal just needs to be re-run, and it's generated files checked in? I'm fairly new to autotools, so it's not entirely clear to me which should be checked into source control and which should be ignored. My inclination is that anything generated by `./configure` and `make` should be ignored, but other files should be included and tracked in source control. This makes it easier for people to contribute source changes without having to have exactly the right version of autotools. I don't have aclocal-1.13 available on either of my test systems (Ubuntu LTS and manjaro), so it's hard for me to experiment with resolving this myself.

**Comment by disheng222** [comment]
Hi Bryce,
OK.
Let me replace the SZ github by the content of tarball, and hope the error
is gone.
In fact, I used automake tool to generate the installation package. It
automatically removes the files which will be generated by configure
command and make command.

Best,
Sheng

2017-02-14 14:36 GMT-06:00 Bryce Allen <notifications@github.com>:

**Comment by disheng222** [comment]
Hi Bryce,
Problem solved.
The reason seems to be "the timestamps got confused somehow".
Please pull the repo and try again.

Best,
Sheng

2017-02-14 14:43 GMT-06:00 Sheng Di <disheng222@gmail.com>:

**Comment by disheng222** [comment]
Hi Bryce,
I introduced a careless bug in the last commitment.
Please pull it again.

Best,
Sheng

2017-02-14 15:18 GMT-06:00 Sheng Di <disheng222@gmail.com>:

**Comment by bd4** [comment]
Thanks, that fixed the issue, I can build from the latest github checkout now.
