### ISSUE TITLE
improve error handling and remove all exit calls

### ISSUE THREAD

**Issue by bd4** [disheng222/SZ#7]
There are many places in the code that call `exit()`. This is problematic for applications that are using SZ for non critical operations and/or want more control over their error handling.

**Comment by disheng222** [comment]
Hi Bryce,
I can replace all those exit() by error codes.
Do you still have the compilation issue?
I tested the compilation on different machines, but couldn't reproduce the
errors you mentioned.
Could you refresh your git repo or download the code from the website, and
try it again?
I remember I encountered the error issue when I modified the Makefile or
something like this before.

Best,
Sheng

2017-02-14 13:37 GMT-06:00 Bryce Allen <notifications@github.com>:
