### ISSUE TITLE
user manual: 2d array dimension example error?

### ISSUE THREAD

**Issue by bd4** [disheng222/SZ#8]
In the manual pages 6-7, it says that that if the data array is 2d (M x N), then args should be r5=0, r4=0, r3=0, r2=M, r1=N. Usually M x N means M rows and N cols, and C 2d arrays use row major order, so shouldn't it be r2=N, r1=M?

**Comment by disheng222** [comment]
Hi Bryce,
r2=M, r1=N is consistent with C style (row major).
r_i means the i-th dimension. For a 3d data (20x30x50), then r3=20, r2=30,
and r1=50.

Best,
Sheng

2017-02-15 14:42 GMT-06:00 Bryce Allen <notifications@github.com>:

**Comment by jychoi-hpc** [comment]
I have similar confusion.

> r2=M, r1=N is consistent with C style (row major).
> r_i means the i-th dimension. For a 3d data (20x30x50), then r3=20, r2=30,
> and r1=50.


I thought r1=M and r2=N for 2d MxN data and r1=20, r2=30, and r3=50 for 3d data (20x30x50).

In https://en.wikipedia.org/wiki/Row-_and_column-major_order, it says
"In row-major order, the last dimension is contiguous"

In our example, I thought N and 50 is the size of the last dimension.

If this is not the case, I need to make some changes in Adios too which is not difficult. I just need some clarification.

Thanks,
Jong

-- 
Jong Youl Choi
Scientific Data Group
Computer Science and Math Division
Oak Ridge National Laboratory
Homepage: http://www.ornl.gov/~jyc/

**Comment by disheng222** [comment]
Hi all,
Let me clarify it.

2017-02-15 15:38 GMT-06:00 Jong Choi <notifications@github.com>:

> I have similar confusion.
>
> > r2=M, r1=N is consistent with C style (row major).


> > r_i means the i-th dimension. For a 3d data (20x30x50), then r3=20,
> r2=30,
> > and r1=50.
>
>
> I thought r1=M and r2=N for 2d MxN data and r1=20, r2=30, and r3=50 for 3d
> data (20x30x50).
>
> No. r2 means the second dimension, which referes to row in 2d data.
I guess I have an example in the user guide, but may be not that clear.
I'll double-check it later. Sorry for possible confusions.

> In https://en.wikipedia.org/wiki/Row-_and_column-major_order, it says
> "In row-major order, the last dimension is contiguous"
>
It's consistent with C style. for a 4D data, r1 is the fasteset changing
dimension and r4 is the slowest. That is, it should be r4xr3xr2xr1.
Please also note that the input parameters of the testing executable (i.e.,
testfloat_compress) adopts the opposite orders.
Anyway, the order of the parameters for *C compression interface* is
consistent with C style (row major).

>
> In our example, I thought N and 50 is the size of the last dimension.
>
> If this is not the case, I need to make some changes in Adios too which is
> not difficult. I just need some clarification.
>
Thanks,
> Jong
>
> --
> Jong Youl Choi
> Scientific Data Group
> Computer Science and Math Division
> Oak Ridge National Laboratory
> Homepage: http://www.ornl.gov/~jyc/
>

**Comment by jychoi-hpc** [comment]
> It's consistent with C style. for a 4D data, r1 is the fastest changing
> dimension and r4 is the slowest. That is, it should be r4xr3xr2xr1.
> Please also note that the input parameters of the testing executable (i.e.,
> testfloat_compress) adopts the opposite orders.
> Anyway, the order of the parameters for *C compression interface* is
> consistent with C style (row major).

I see. As a summary, in your interface definition, for N dimensional array, r1 is the fastest changing dimension and rN is the slowest dimension. 

In C, this will be (rN, ..., r1). In Fortran, it will be (r1, ..., rN). 

Is that right? 

If you can update the manual in that way, it will be clear to users.

Thanks,
Jong

**Comment by disheng222** [comment]
2017-02-15 16:52 GMT-06:00 Jong Choi <notifications@github.com>:

**Comment by bd4** [comment]
I agree that saying r1 is fastest and rN is slowest changing is a good way to explain it. A specific example for C vs Fortran is also helpful.
